---
classes:
 - foodity-mysql
 - foodity-apache
 - foodity-java


##########################MYSQL####################

mysql::server::old_root_password: ''
mysql::server::root_password: 'rewit555'
mysql::server::config_file: '/etc/mysql/my.cnf'
mysql::server::manage_config_file: true
 
mysql::server::databases:
    'service':
      charset: 'utf8'
      ensure: 'present'

mysql::server::users:
  'claudio@localhost':
    ensure: 'present'
    password_hash: '*7ACE763ED393514FE0C162B93996ECD195FFC4F5'
  'service@localhost':
    ensure: 'present'
    password_hash: '*C80A94EF37B4CA1599BA47CC95530C43CACD7DA5'


#############################APACHE#######################


apache_folders:
    '/var/www/service':
      path: '/var/www/service'
      ensure: 'directory'
      mode: '0664'
      owner: 'www-data'
      recurse: 'true'
    '/var/www/service/www':
      path: '/var/www/service/www'
      ensure: 'directory'
      mode: '0664'
      owner: 'www-data'
      recurse: 'true'
      require: "File[/var/www/service]"
    '/var/www/service/www/public':
      path: '/var/www/service/www/public'
      ensure: 'directory'
      mode: '0664'
      owner: 'www-data'
      recurse: 'true'
      require: "File[/var/www/service/www]"

apache_vhosts:
  'service':
    port: '80'
    servername: 'service.foodity.com'
    docroot: '/var/www/service/www/public'
    access_log: true
    access_log_file: 'access.log'
    access_log_format: 'combined'
    error_log: true
    error_log_file: 'error.log'
    options:
      - '-Indexes'
    php_admin_values:
      - 'open_basedir /var/www/service:/tmp'
      - 'upload_tmp_dir /var/www/service/tmp'
      - 'register_globals off'
    require: 'File[/var/www/service/www/public]'
